# Generated by Django 4.1.1 on 2022-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Нажми сверху, чтобы прочитать пост полностью...', max_length=255, verbose_name='Категория'),
        ),
    ]
