# Generated by Django 4.1.1 on 2022-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Нажми сверху, чтобы прочитать пост полностью...', max_length=255),
        ),
    ]
